### ISSUE TITLE
Enhancement request: Colored timeout/lost packet

### ISSUE THREAD

**Issue by gustavhelgi** [famzah/ping-multi#7]
Hi

First of thanks for an awesome product, it's really helpful in many situations. I use it when doing network work to verify connectivity from hosts. 
I hope you are still following this and can help with a small enhancement.

There are scenarios i have long test lists or multiple windows to multiple hosts to verify connections. Would be great to have a RED coloring on the X or "host line" line so it can be spotted quicker among multiple windows/lines.

**As a side note it could be taken further to add color to enhance spotting issues but not really a request just something to think about if you want to take it further :)**
Like orange to spot changes like 30% increase in RTT
Or have the host change color from RED (during) to orange to yellow to white depending on length since packetloss.

Again thanks for this,

Gustav

**Comment by famzah** [comment]
Hi Gustav, I'm glad that "ping-multi" is working well for you, too! Coloring is something that we can try, yes.

For my own work I migrated to the new implementation of "ping-multi" which runs multiple standard "ping" binaries in parallel. I went this way because something in the Perl implementation is not entirely correct in regards to timing. The readings in Perl are correct but not all pings are scheduled at the same time and this bugs me too much.

Please try the new implementation:
```python
pip3 install ping-multi-ext
```

The command line interface is more or less the same. Additionally, you get the following new features:
- scrollable window, if you have lots of hosts
- when you have selected a host and press Enter, you see the output of the "ping" command; also scrollable

If you also prefer the new "ping-multi-ext", I'd rather do further development there.

Let me know what you think.

**Comment by gustavhelgi** [comment]
Hi Ivan,

Wow, thanks for your quick reply...yeah of course i´ll try the ping-multi-ext tomorrow and then just open a Enhancement request there, no need to cover two things if you are focusing on the other side :).

**Comment by famzah** [comment]
A quick note: I've just completed the README and finally made the project public: https://github.com/famzah/ping-multi-ext
